version: '1.0'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    expose:
    - "3306"
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/kamin/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/kamin/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge